### ISSUE TITLE
Cannot add my repo

### ISSUE THREAD

**Issue by dijs** [gitcheese/gitcheese.ui#1]
I added gitcheese to my repo long ago, but now, with the changes, my badge is broken and I cannot add my repo again... I went to the "Dashboard", but only 16 of my repos showed up and "wikijs" was not one of them.

**Comment by mgibas** [comment]
Yeah, it looks like you should see at least 48 repositories - looking into it

**Comment by mgibas** [comment]
Found issue: https://github.com/gitcheese/gitcheese.api/issues/1
That should be take care of today/tomorrow

**Comment by dijs** [comment]
Thanks
