### ISSUE TITLE
IBAN Error

### ISSUE THREAD

**Issue by Radeox** [gitcheese/gitcheese.ui#5]
When I insert my IBAN I get this error
![screenshot_20170603_122000](https://cloud.githubusercontent.com/assets/9751015/26752721/fde7e62e-4856-11e7-87ac-661c51d045fb.png)

**Comment by mgibas** [comment]
Seems like stripe API requires currency right now - will take care of this

**Comment by mgibas** [comment]
Added currency selection - let me know if u have any issues
